language: Ruby
dist: focal
arch:
  - amd64
  - ppc64le
before_script:
  - sudo apt update -y
  - sudo apt-get install maven
script:
  - mvn clean install -DskipTests
  - mvn clean install -DskipTests -Dfull
  - cd ..
  - droolsjbpm-build-bootstrap/script/mvn-all.sh -DskipTests clean install
  - cd droolsjbpm-build-bootstrap/
  - mvn test
  - mvn clean verify -Pcode-coverage
  - mvn verify -Dmutation-coverage
  - mvn verify -Dmutation-coverage -DtargetClasses=org.drools*
